<?php

namespace Zak\Lists\Fields;

use Carbon\Carbon;

class Date extends Text
{
    public array $rules = [
        'date' => 'Неправильная дата'
    ];
    public bool $time = false;

    public function withTime(): static
    {
        $this->time = true;
        return $this;
    }

    public function type(): string
    {
        return $this->time ? 'datetime-local' : 'date'; // TODO: Change the autogenerated stub
    }

    public function saveHandler($item, $data)
    {
        $value = $data[$this->attribute] ?? '';
        if ($value) {
            $item->{$this->attribute} = Carbon::make($value);
        }
        return $item;
    }
    public function handleFill()
    {
        $this->value = $this->item->{$this->attribute};
        $format = $this->time ? "Y-m-d H:i" : 'Y-m-d';
        $this->value=$this->value && $this->value instanceof Carbon ? $this->value->format($format) : $this->value; // TODO: Change the autogenerated stub
    }

    public function indexHandler()
    {
        $value = $this->item->{$this->attribute};
        $format = $this->time ? "d.m.Y | H:i" : ' d.m.Y';
        if ($value instanceof Carbon) {
           $this->value= "<span class='text-center'>".str_replace('|', "<br>", $value->format($format))."</span>";
        } elseif ($value) {
           $this->value= "<span class='text-center'>".str_replace('|', "<br>", date($format, strtotime($value)))."</span>";
        }else{
            $this->value='';
        }
    }

    public function detailHandler()
    {
        $this->indexHandler();
    }
}
